---
- name: install pip
  yum: name=python-pip state=installed
- name: install supervisord
  pip:
    name: supervisor
    state: present
    extra_args: -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
